import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Footer from "../components/shared/Footer";
import Navbar from "../components/shared/Navbar";
import ReactQueryProvider from "../components/shared/ReactQueryProvider";
import "./globals.css";
const roboto = Roboto({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "News-Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={roboto.className}>
          <Navbar />
          <main className="max-w-7xl mx-auto py-20">
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
